version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: exam-postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
      PGDATA: ${PG_DATA}
    volumes:
      - ./data/:${PG_DATA}
      - ./init-scripts/:/docker-entrypoint-initdb.d
    ports:
      - '${PG_PORT}:5432'

volumes:
  data: